FROM ubuntu:18.04

RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install python3.6 -y
RUN ln -s /usr/bin/python3.6 /usr/bin/python3
RUN ln -s /usr/bin/python3 /usr/bin/python
RUN apt-get install git -y
# add whatever ubuntu packages here

